name: Publish
on:
  push:
    tags:
      - "v*"
jobs:
  tagged-release:
    name: Upload file-builded as release assets
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.x
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: build-linux
        run: GOOS=linux GOARCH=amd64 go build -o hs main.go
      - name: build-windows
        run: GOOS=windows GOARCH=amd64 go build -o hs.exe main.go
      - name: build-macos
        run: GOOS=darwin GOARCH=amd64 go build -o hs-macos main.go
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GHPAT }}"
          prerelease: false
          files: |
            hs
            hs.exe
            hs-macos
